on:
  push:
    branches: [ main, avdim ]
  pull_request:
    branches: [ main, avdim ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: ./integration_test.sh
#     - run: npm run build --if-present
#     - run: npm test
